# Generated by Django 3.0.4 on 2021-12-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_category_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('financiero', 'Financiero')], default='financiero', max_length=10, verbose_name='Fin')),
                ('ciudad', models.CharField(choices=[('loja', 'Loja'), ('catamayo', 'Catamayo')], default='loja', max_length=10)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('ext_Ip', models.CharField(max_length=150, verbose_name='Ext_IP')),
                ('celular', models.CharField(max_length=150, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254)),
                ('funciones', models.CharField(max_length=250)),
            ],
        ),
    ]
