# Generated by Django 3.0.4 on 2021-12-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_directorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio',
            name='departamento',
            field=models.CharField(choices=[('financial', 'Financiero'), ('Logistics', 'Logística'), ('Marketing', 'Marketing'), ('SSADT', 'SSADT'), ('Talent Human ', 'Humano'), ('tic', 'TIC'), ('exp', 'Exp')], default='financiero', max_length=250, verbose_name='Fin'),
        ),
    ]
